# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n\rStreamRequest\"Y\n\rImageResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\n\n\x02id\x18\x02 \x01(\x05\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2B\n\x0cImageService\x12\x32\n\x0cStreamImages\x12\x0e.StreamRequest\x1a\x0e.ImageResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STREAMREQUEST']._serialized_start=48
  _globals['_STREAMREQUEST']._serialized_end=63
  _globals['_IMAGERESPONSE']._serialized_start=65
  _globals['_IMAGERESPONSE']._serialized_end=154
  _globals['_IMAGESERVICE']._serialized_start=156
  _globals['_IMAGESERVICE']._serialized_end=222
# @@protoc_insertion_point(module_scope)
